In [2]:
Y = [83, 85, 84, 85, 85, 86, 86, 87, 86, 
     87, 87, 87, 88, 88, 88, 88, 88, 89, 
     90, 89, 90, 90, 91, 90, 92]
Psi = [(1, 0, 0, 0, 0) for _ in range(2)] + [(0, 1, 0, 0, 0) for _ in range(6)] + \
        [(0, 0, 1, 0, 0) for _ in range(11)] + [(0, 0, 0, 1, 0) for _ in range(4)] + \
        [(0, 0, 0, 0, 1) for _ in range(2)]


In [22]:
import numpy as np
from scipy.stats import t
import matplotlib.pyplot as plt


def make_regression(Psi, Y):
    Psi = np.array(Psi)
    Y = np.array(Y)
    F = np.dot(Psi.transpose(), Psi)
    F_1 = np.linalg.inv(F)
    betta_est = np.dot(np.dot(F_1, Psi.transpose()), Y)
    e = np.dot(Psi, betta_est) - Y
    RSS = np.dot(e.transpose(), e)
    return betta_est, RSS, F

In [14]:
betta_est, RSS, F = make_regression(Psi, Y)
print("F =", F)
F_1 = np.linalg.inv(F)
print("betta_est =", betta_est)
print("RSS =", RSS)
y_aver = sum(Y) / len(Y)
TSS = sum([(y - y_aver) ** 2 for y in Y])
print("TSS =", TSS)
print("R**2 =", (TSS - RSS) / TSS)

F = [[ 2  0  0  0  0]
 [ 0  6  0  0  0]
 [ 0  0 11  0  0]
 [ 0  0  0  4  0]
 [ 0  0  0  0  2]]
betta_est = [84.         85.5        87.81818182 90.         91.        ]
RSS = 23.136363636363637
TSS = 122.16
R**2 = 0.8106060606060606


In [20]:
deltas = []
n = 25
p = 5
for i in range(1, 5):
    d = []
    for j in range(i):
        d.append(abs(betta_est[i] - betta_est[j]) / (RSS * (F_1[i][i] + F_1[j][j])) ** 0.5 \
                 * (n - p) ** 0.5)
    deltas.append(d)
print(*deltas, sep="\n")

[1.70806477196444]
[4.618104080188217, 4.246806265625998]
[6.441515642463517, 6.481650084604495, 3.474295168162988]
[6.5082688827896185, 6.262904163869613, 3.848420066823525, 1.073585940410586]


In [35]:
p_values_print = []
p_values = []
for i in range(1, 5):
    p_v = []
    for j in range(i):
        p_v.append(2 * (1 - t.cdf(deltas[i - 1][j], n - p)))
        p_values.append(2 * (1 - t.cdf(deltas[i - 1][j], n - p)))
    p_values_print.append(p_v)
print(*p_values_print, sep='\n')


[0.10310040890082361]
[0.0001662014487755492, 0.00039504010033408754]
[2.7821115005099983e-06, 2.5534724907849693e-06, 0.0023933387043622023]
[2.4125702768884594e-06, 4.085183105129175e-06, 0.0010025629060046448, 0.29579135227474707]


In [34]:
p_values = sorted(p_values)
m = len(p_values)
alpha = 0.05
for i in range(len(p_values)):
    if p_values[i] < alpha / m:
        print(f"p_value = {p_values[i]} < alpha / m = {alpha / m}, bi != bj")
        m -= 1
    else:
        print(f"p_value = {p_values[i]} > alpha / m = {alpha / m}, bi == bj")

p_value = 2.4125702768884594e-06 < alpha / m = 0.005, bi != bj
p_value = 2.5534724907849693e-06 < alpha / m = 0.005555555555555556, bi != bj
p_value = 2.7821115005099983e-06 < alpha / m = 0.00625, bi != bj
p_value = 4.085183105129175e-06 < alpha / m = 0.0071428571428571435, bi != bj
p_value = 0.0001662014487755492 < alpha / m = 0.008333333333333333, bi != bj
p_value = 0.00039504010033408754 < alpha / m = 0.01, bi != bj
p_value = 0.0010025629060046448 < alpha / m = 0.0125, bi != bj
p_value = 0.0023933387043622023 < alpha / m = 0.016666666666666666, bi != bj
p_value = 0.10310040890082361 > alpha / m = 0.025, bi == bj
p_value = 0.29579135227474707 > alpha / m = 0.025, bi == bj
